def personasAppend(bigList,key,list):
  bigList.append(dict(zip(key,list)))
  return None


keys = ['name','arcana','startinglevel','inherits','reflects','absorbs','blocks','resists','weak','img','info']

izanagi = ['Izanagi','Fool','1','Electric','-','-','Dark','Electric','Wind','img/Izanagi.jpg','Izanagi is a Japanese creation deity born of the seven divine generations in Japanese mythology. He is also referred to in various chronicles such as the Kojiki and Nihon Shiki as Izanagi-no-mikoto, the "male-who-invites". He and Izanami created many of the islands and deities of Japan. When Izanami died, Izanagi tried to retrieve her from the underworld, but failed. He mistakenly looks at her while shes in a rotting, monstrous state in the underworld, which shames her. She attempts to kill him, and swears to kill a thousand of his men a day. Izanagi claims that he will make sure that a thousand and five hundred will be born each day.']
yomotsu_shikome = ['Yomotsu-Shikome','Fool','7','Negative Status','-','-','-','Ice','Fire','img/Yomotsu_Shikome.jpg','The Yomotsu-shikome in Japanese mythology are residents of the underworld, or Yomi. In the myth, Izanagi, longing to be with his deceased wife Izanami, attempted to retrieve her from the Yomi. When he saw Izanamis rotten and ugly self, he ran away, and Izanami ordered the Yomotsu-Shikome, the "old hags of the Yomi" to chase after him. Izanagi slowed them down by throwing down his headdress and sacred comb, which turned into grapes and bamboo shoots respectively, and caused the Shikome to stop and eat the food, enabling Izanagi to escape the underworld.']
pixie = ['Pixie','Magician','2','Ice','-','-','-','Wind','Fire','img/Pixie.jpg','According to the local folklore of southwest England, pixies are small mischievous creatures that inhabit the countryside and woodlands that like to play pranks on humans. Depending on the tale told, pixies can vary in size from tiny enough to fit in the palm of a humans hand to the size of a small child, although they are always a good deal below the size of an average human. They can be portrayed with or without wings, and over the years have taken on many traits usually associated with fairies, often leading to the common misconception that they are one and the same.']
orobas = ['Orobas','Magician','8','Fire','-','-','-','Fire','Ice','img/Orobas.jpg','According to the Lesser Key of Solomon, Orobas is the 55th spirit and a prince of Hell who could give conjurers perfect information about the past, present, or future, bestow honors, reconcile them with foes, and protect them from being tempted by demons. He would never deceive anyone. He commands 20 legions of spirits (26 according to Harley 6483, considered the least reliable of the manuscripts).']
saki_mitama = ['Saki Mitama','Priestess','11','Recovery','-','-','-','Ice','Wind','img/SakiMitama.png','One of the four great aspects of Shinto thought, it brings great bounty from the hunt. It is said to aid in love, profit, and growth, and can create new paths.']
sarasvati = ['Sarasvati','Priestess','17','Recovery','-','-','Ice','-','Wind','img/Sarasvati.jpg','Hindus believe that Sarasvati is the goddess of knowledge, music and the arts. Sarasvati has been identified with the Vedic Sarasvati River. She is considered as consort of Brahma, the Hindu god of creation. Thus, with the goddesses Lakshmi and Parvati or Durga, she forms the Tridevi, who are consorts of the male trinity of Brahma, Vishnu and Shiva, respectively. Sarasvatis children are the Vedas, which are the oldest sacred texts of Hinduism. She is known in East Asia as Benzaiten or Biancaitian ( lit. "God of wisdom and wealth"), one of the Seven Lucky Gods.']
senri = ['Senri','Empress','9','Recovery','-','-','Fire','-','Electic','img/Senri.jpg','"In Japanese folklore, the senri are creatures that come into being when an extremely old mountain cat undergoes a spiritual transformation. It can take the form of a beautiful young lady and seduce unfortunate men that wonder into the mountains. It then steals their life energy in order to sustain itself and gain more power. The senri is the highest rank of bakeneko, and it is said that other animals that have become demonized gather life energy so that they themselves can become Senri. The senri are akin to the Chinese spirit animals known as the yao jing, which achieve human form after many years of training in the art of Taoism.']
yaksini =  ['Yaksini','Empress','18','Ice','-','-','Ice','Electric','Fire','img/Yaksini.jpg','A yaksini  is the female counterpart of the male yaksa, and they both attend to Kubera (also called Kuber), the Hindu god of wealth who rules in the mythical Himalayan kingdom of Alaka. They both look after treasure hidden in the earth and resemble fairies. Yaksini are often depicted as beautiful and voluptuous, with wide hips, narrow waists, broad shoulders, and exaggerated, spherical breasts. In the Uddamareshvara Tantra, thirty-six yaksini are described, including their mantras and ritual prescriptions. A similar list of yaksas and yaksini is given in the Tantraraja Tantra, where it says that these beings are givers of whatever is desired.']
oberon = ['Oberon','Emperor','12','Electric','-','-','Electric','Fire','Wind','img/Oberon.jpg','The King of the Fairies and the husband of Titania, the Fairy Queen. He rules over moonlight, dreams, and all fairy rites. He first became widely known when he appeared as a character in Shakespeares "A Midsummer Nights Dream," but appeared earlier in the 13th century French epic "Huon of Bordeaux." In some stories, specifically in "Huon of Bordeaux," it is said that he is the son of Morgan le Fey and Julius Caesar, believed to have been born sometimes after Caesars defeat of Pompey.']
king_frost = ['King Frost','Emperor','22','Ice','-','Ice','-','-','Fire','img/King_Frost.png','Most likely came from The Frost Fairies, a story written by Margaret T. Canby about King (Jack) Frost, a kind fairy king from the cold North.']
omoikane = ['Omoikane','Hierophant','7','Electric','-','-','-','Electric','Ice','img/Omoikane.jpg','Omoikane is a Shinto god of wisdom and intelligence. His name means "serving ones thoughts." A heavenly deity, identified as a child of Takami-Musubi, who is always called upon to "ponder" and give good counsel in the deliberations of the heavenly deities. Appears to have descended from the heavens in the heavenly descent myth. Omoikane was a deity of wisdom or good counsel able to hold many thoughts at once or to combine in one mind the mental powers of many individuals.']
anzu = ['Anzu','Hierophant','15','Wind','-','-','Wind','Electric','Fire','img/Anzu.jpg','Anzu, mainly known as Zu, was a demonic tempest bird in Mesopotamian mythology, known for stealing the Tablet of Destinies from Enlil, the lord of the wind. These specific tablets gave the power to whomever possessed them to control the universe. The supreme god Anu promised sovereignty over the gods to whoever recovered the tablets from Anzu. Due to the surviving texts being in fragments, its unclear to establish the outcome, but it seems that either the god Marduk or Ninurta, Enlils son, recovered the Tablets.']
queen_mab = ['Queen Mab','Lovers','25','Electric','-','-','Electric','-','Wind','img/Queen_mab.jpg','Mab, also known as Medb or Meive, is the queen of Connacht. Famous for her capricious nature and her many lovers, she wages many wars for sake of her continued glory. The Cattle Raid of Cooley makes her cross paths with her archenemy Cu Chulainn, who shamed her numerous times by slaying her pets, warriors and handmaidens.']
undine = ['Undine','Lovers','33','Recovery','-','Ice','-','-','Fire','img/Undine.jpg','Famous medieval German-Swiss chemist Paracelsus coined this term for female water sprites. An elemental is a mythological being first appearing in the alchemical works of Paracelsus. In one story an Undine married a human man who vowed to love her with every breath he took, but when he was unfaithful, she cursed him to stop breathing in his sleep and die. He ultimately passed out from sheer exhaustion and suffocated.']
slime = ['Slime','Chariot','2','Physical','-','-','-','Physical','Fire','img/Slime.jpg','In the Dungeons & Dragons fantasy role-playing game, an ooze is a type of creature. This category includes such monsters as slimes, jellies, deadly puddings, and similar mindless, amorphous blobs. They can be used by Dungeon Masters as enemies or allies of the player characters. Many oozes dwell underground, and most secrete an acid from their skin that dissolves flesh and other materials rapidly. Oozes are essentially blind, but more than make up for that with an ability called "blindsight", which allows them to discern nearby objects and creatures without needing to see them visually.']
nata_taishi = ['Nata Taishi','6','Physical','-','-','-','Fire','Electric','img/Nata_Taishi.png','According to Fengshen Yanyi, Nezha was born during the Shang Dynasty in a military fortress at Chentang Pass. His father was a military commander named Li Jing, who became the "Pagoda-wielding Heavenly King" later. Nezhas mother, Lady Yin, gave birth to a ball of flesh after being pregnant with him for three years and six months. Li Jing thought that his wife had given birth to a demon and he attacked the ball with his sword. The ball split open and Nezha jumped out as a boy instead of an infant. Nezha could speak and walk immediately after birth. He is accepted by the immortal Taiyi Zhenren as a student later. He had two older brothers, Jinzha, a disciple of Manjusri Bodhisattva, and Muzha, a disciple of Samantabhadra Bodhisattva. Nezha is often depicted as a youth, instead of an adult. He is often shown flying in the sky riding on the Wind Fire Wheels, a golden hoop around his body (sometimes on his left hand), a red sash around his shoulder and a Fire Spear in his right hand. Sometimes, he is shown having three heads and six arms. He has the ability to spit fire in some legends.']
angel = ['Angel','Justice','4','Wind','-','-','-','Wind, Light','Dark','img/Angel.jpg','Angels have been recorded in various religious lore as celestial beings who faithfully serve God.']
archangel = ['Archangel','Justice','Light','-','-','light','-','Darkness','img/Archangel.png','In the nine orders of angels in Christian teachings, archangels are among the eighth, making them second in the third hierarchy. Archangels are one of the few bodies of angels that contact those on the material plane directly and are the ministers and messengers between God and mankind. Some of the most famous archangels include Michael and Gabriel who both appear in the Bible, although only Michael was named expressly as an archangel. The Jewish name for it is rav-mal ákh.']
forneus = ['Forneus','Hermit','6','Ice','-','-','Dark','Ice','Electric','img/Forneus.jpg','According to the writings in The Lesser Key of Solomon, Forneus is the thirtieth spirit listed in the Goetia. He is a Great Marquis of Hell with twenty-nine legions under his command, partly comprised of the order of Angels and Thrones, and appears as a sea monster. When summoned, he can make men well-versed in rhetoric, give him a good name, teach him foreign tongues, and make him trusted by friend and foe alike.']
ippon_datara = ['Ippon Datara','Hermit','Darkness','-','-','Darkness','Fire','Light','img/Ippon_Datara.jpg','A rarely seen creature, one is more likely to see his footprints on the mountains. Some believe he might be a blacksmith or the ghost of one.']
fortuna = ['Fortuna','Fortune','35','Wind','-','-','Fire, Wind','-','-','img/Fortuna.jpg','The goddess of Fortune and luck in Roman mythology, daughter of Jupiter, and hopefully brought good luck. She can be represented veiled or blind. Used to be a goddess of blessing and fertility, mainly being worshiped by mothers.']
clotho = ['Clotho','Wind','Wind','-','-','-','-','img/Clotho.jpg','Clotho is one of the three Moirae Sisters, and is derived from the Greek personification of fate. The youngest, Clotho spins the thread of life.']
sandman = ['Sandman','Strength','5','Wind','-','-','-','Wind','Electric','img/Sandman.jpg','Originating from Northern European lore, he brings good dreams by sprinkling magical sand onto the eyes of children while they sleep at night. The rheum in ones eyes upon waking is believed to be the result of the Sandmans work the previous evening.']
valkyrie = ['Valkyrie','Strength','8','Ice','-','-','-','Ice','Wind','img/Valkyrie.png','In Norse mythology, a valkyrie (from Old Norse valkyrja "chooser of the slain") is one of a host of female figures who decide who will die in battle. The valkyries bring their chosen to the afterlife hall of the slain, Valhalla, ruled over by the god Odin, where the deceased warriors become einherjar. There, when the einherjar are not preparing for the events of Ragnarök, the valkyries bear them mead. Valkyries also appear as lovers of heroes and other mortals, where they are sometimes described as the daughters of royalty, sometimes accompanied by ravens, and sometimes connected to swans.']
berith = ['Berith','Hanged Man','15','Physical','-','-','Fire','-','Wind','img/Berith.jpg','According to the writings in The Lesser Key of Solomon, Berith is the twenty-eighth spirit listed in the Goetia. He rides a gigantic red horse and burns those without manners. He is a Great Duke of Hell with twenty-six legions of demons under his command. He is depicted as a knight or soldier wearing red armour and a golden crown. In order to speak with him the conjurer must wear a silver ring and hold it before his face. He gives true answers to all things past, present and future as long as he is asked, but when not answering questions is a liar. He can turn any metal into gold, give dignities and confirm them.']
yomotsu_ikusa = ['Yomotsu-Ikusa','Hanged Man','Aliment','-','-','Darkness','Ice','Fire','img/Yomotsu_Ikusa.jpg','Yomotsu-Ikusa, or the army of Yomi, were beings which were led by the Yomotsu-Shikome to pursue Izanagi when he fled the underworld after seeing Izanamis face after her death.']
ghoul = ['Ghoul','Death','9','Ailment','-','-','Ice','-','Fire, Light','img/Ghoul.jpg','Demon of ancient Arabian folklore. The word "ghoul" is Arabic for "demon," referring to creatures who were believed to dwell in graveyards and abandoned places.']
mokoi = ['Mokoi','Death','14','Support','-','-','Ice','-','Fire','img/Mokoi.png','In Australian folklore, Mokoi are spirits of evil who kill those who used dark magic. They would also kidnap and eat children at night.']
apsaras = ['Apsaras','Temperance','4','Recovery','-','-','-','-','Fire','img/Apsaras.jpg','Apsaras also known as Vidhya Dhari, according to Hindu and Buddhist mythology, are spirits that appear in the form of young, beautiful women who have mastered the fine art of celestial dance. They are the wives of Indras servants, Gandharvas, and are known to entertain the gods and fallen heroes, dancing in the divine palaces to music made by their husbands. They are frequently equated with the water-elemental nymphs and naiads of Ancient Greeks, and depictions of them can be seen in Cambodian and Balinese culture.']
sylph = ['Sylph','Temperance','11','Wind','-','-','-','Wind','Electric','img/Sylph.jpg','An air elemental known as Sylph is a mythological being first appearing in the alchemical works of Paracelsus. He describes sylphs as invisible beings of the air.']
ukobach = ['Ukobach','Devil','3','FIre','-','-','-','Fire','Ice','img/Ukobach.png','A lesser demon of Hell. Ukobach has no free will and will only follow the commands of higher demons. He is in charge of maintaining the oil in the infernal boilers, and will often torture the souls trapped in Hell. Ukobachs only ability is to start fires.']
lilim = ['Lilim','Devil','10','Darkness','-','-','-','Darkness','Light','img/Lilim.png','In Jewish folklore, lilin (or lilim) were dangerous creatures. They were said to be the children of Lilith by Samael, the angel of death. They are demons and are similar to succubi. Men feared the lilim for this reason and women also feared the lilim because it is believed that they kidnap children like their mother Lilith.']
tao_tie = ['Tao Tie','Tower','35','Almighty','Dark','-','-','-','-','img/Tao_tie.jpg','The Taotie, also known by its Japanese name Toutetsu, is said to be a Chinese monster of unknown origin. It is said that it is a greedy monster with an insatiable appetite, and as punishment, only its head remains. Fear of the monster led its image to be cast on Chinese bronzes and ritual vessels. Along with Taown, Hun Dun and Qiong Qi, it is one of the Four Fiends, prominent Chinese demons representing evil virtues. Tao Tie represents gluttony.']
cu_chulainn = ['Cu Chulainn','Tower','46','Wind','Wind','-','-','Physical','Ice','img/Cu_chulainn.jpg','Cu Chulainn is an Irish mythical hero who appears in the stories of the Ulster Cycle, as well as in Scottish and Manx folklore. The son of the god Lugh and Deichtine (sister of the king of Ulster), he was originally named Setanta, but gained his better-known name as a child after he killed Culanns fierce guard-dog in self-defense, and offered to take its place until a replacement could be reared. At the age of seventeen he defended Ulster single handedly against the armies of queen Medb of Connacht in the epic Tain Bo Cuailnge. It was prophesied that his great deeds would give him everlasting fame, but that his life would be short – one reason he is compared to the Greek hero Achilles. He is known for his terrifying battle frenzy, in which he becomes an unrecognizable monster who knows neither friend nor foe. He fights from his chariot, driven by his loyal charioteer Laeg, and drawn by his horses, Liath Macha and Dub Sainglend. Many say he acquired a lot of power by submitting himself to some geis, two of which are "Ill never eat dog meat" and "Ill never refuse a meal offered by a woman." But then a woman offered him some dog meat, as so he had to choose what geis to break and he accepted the meal. After that, he was forced by Queen Mab to break his geis one by one, as so he met his death at the hands of Lugaid (child of Cu Roi, a man he had to kill to defend Ulster).']
kaiwan = ['Kaiwan','Star','24','Support','-','-','Dark','-','Physical','img/Kaiwan.jpg','An Astro-Mythological deity in Assyrian mythology. He is associated with the planet Saturn. Kaiwan is also one of the names of Hastur the unspeakable in Lovecraftian lore.']
neko_shogun = ['Neko Shogun','Star','32','Support','Electric','-','Light, Dark','Physical','Wind','img/Neko_Shogun.png','"A prophetic Taoist god, originally known as Mao Shogun. Due to a linguistic error involving the Chinese word for cat, his name was changed to Neko Shogun." — Compendium Info']
andras = ['Andras','Moon','20','Recovery','-','-','Electic','-','Wind','img/Andras.jpg','According to the writings in The Lesser Key of Solomon, Andras is the sixty-third spirit listed in the Goetia. He is a Great Marquis of Hell with thirty legions of demons under his command. He is depicted as a humanoid with an angels wings and an owls head, riding a black wolf and holding a bright sword. Among the spirits of the Goetia, Andras is one of the most violent and dangerous to summon. The conjurer and any attendants he may have must stay within a magic circle at all times no matter how much Andras tempts them to leave it, or he will surely kill them. He is able to control a persons anger or inflict rage upon any person the conjurer desires and tempt people to kill their servants or masters. If so asked, Andras will gladly kill any person the conjurer desires, and in certain demonology it is suggested that Flauros is his servant.']
nozuchi = ['Nozuchi','Moon','27','Status','Electric','-','-','-','Ice','img/Nozuchi.jpg','In Japanese mythology, the Nozuchi or Nodzuchi is a spirit of the earth that is found in open plains hiding in the shadows of the plants and trees. While it is not an evil or mischievous spirit, it is wild and uncontrollable, thus it will sometimes bring harm to humans it sees as intruders or threats. Its name means "God of the plains". It is also another name for the serpent monster Tsuchinoko, which is now seen more as a cryptid that takes the form of a fat snake.']
cu_sith = ['Cu Sith','Sun','10','Wind','-','-','-','Wind','Fire','img/Cu_sith.jpg','Cu Sith (pronounced Coo Shee) is a giant otherworldly dog which haunts the Scottish highlands and fairy mounds. It is said to be roughly the size of a horse and have shaggy green fur with a long often braided tail. Cu Sith, though capable of hunting silently, would often let out three terrifying barks, which could be heard over long distances. These three barks would herald the coming of Cu Sith and warn farmers and sailors to lock up their women at night, lest the great hound come and snatch them away to supply milk for the fairy children.']
feng_huang =['Feng Huang','Sun','20','Wind','-','-','Electric','-','Ice','img/Feng_Huang.jpg','Fenghuang are mythological birds of East Asia that reign over all other birds. The males are called Feng and the females Huang. In modern times, however, such a distinction of gender is often no longer made and the Feng and Huang are blurred into a single feminine entity so that the bird can be paired with the Chinese dragon, which has male connotations. The Fenghuang is also called the "August Rooster" since it sometimes takes the place of the Rooster in the Chinese Zodiac. It is occasionally confused with the Suzaku, although non-Han variations of the Four Symbols consider both the Suzaku and the Feng Huang as the same creature. Feng Huang is known in Japan as Ho-O, or Houou. Sometimes it is incorrectly called the Chinese Phoenix, which originated from mythologies of different regions.']
anubis = ['Anubis','Judgement','59','Light','-','-','Light','-','-','img/Anubis.jpg','Anubis is widely known as the Egyptian deity of mummification. In this role, he oversees the mummification process of the dead, and is usually seen in hieroglyphic tomb-carvings as overseeing the burial ritual for the pharaohs and those of royal lineage - this is due to the priest involved wearing the masks of Anubis to symbolize him as the overseer of the ritual.']
trumpeter = ['Trumpeter','Judgement','67','Almighty','Electric, Wind','Ice','Dark','-','-','img/Trumpeter.png','The Trumpeter is based on one of the angels mentioned in the Book of Revelation of the New Testament. It is said that seven trumpets will be sound by seven angels, and each trumpet signifies a different event or plague on Earth before the final moments leading to the Apocalypse.']
izanagi_no_okami = ['Izanagi-no-Okami','World','91','No','-','-','-','Physical,Fire, Ice, Electic, Wind','-','img/Izanagi_no_okami.jpg','The name "Okami", which means "Great Deity", symbolizes Izanagis true identity as the deity born of the seven divine generations in Japanese mythology.']


personas = []
personasAppend(personas,keys,izanagi)
personasAppend(personas,keys,yomotsu_shikome)
personasAppend(personas,keys,pixie)
personasAppend(personas,keys,orobas)
personasAppend(personas,keys,saki_mitama)
personasAppend(personas,keys,sarasvati)
personasAppend(personas,keys,senri)
personasAppend(personas,keys,yaksini)
personasAppend(personas,keys,oberon)
personasAppend(personas,keys,king_frost)
personasAppend(personas,keys,omoikane)
personasAppend(personas,keys,anzu)
personasAppend(personas,keys,queen_mab)
personasAppend(personas,keys,undine)
personasAppend(personas,keys,slime)
personasAppend(personas,keys,nata_taishi)
personasAppend(personas,keys,angel)
personasAppend(personas,keys,archangel)
personasAppend(personas,keys,forneus)
personasAppend(personas,keys,ippon_datara)
personasAppend(personas,keys,fortuna)
personasAppend(personas,keys,clotho)
personasAppend(personas,keys,sandman)
personasAppend(personas,keys,valkyrie)
personasAppend(personas,keys,berith)
personasAppend(personas,keys,yomotsu_ikusa)
personasAppend(personas,keys,ghoul)
personasAppend(personas,keys,mokoi)
personasAppend(personas,keys,apsaras)
personasAppend(personas,keys,sylph)
personasAppend(personas,keys,ukobach)
personasAppend(personas,keys,lilim)
personasAppend(personas,keys,tao_tie)
personasAppend(personas,keys,cu_chulainn)
personasAppend(personas,keys,kaiwan)
personasAppend(personas,keys,neko_shogun)
personasAppend(personas,keys,andras)
personasAppend(personas,keys,nozuchi)
personasAppend(personas,keys,cu_sith)
personasAppend(personas,keys,feng_huang)
personasAppend(personas,keys,anubis)
personasAppend(personas,keys,trumpeter)
personasAppend(personas,keys,izanagi_no_okami)

def startDB():
  return personas

